const TemplateEngine = {
    generateNote: function(templateStr, formData, config) {
        if (!templateStr) return "";
        
        let output = templateStr;
        
        // Replace {reusable_*} keys with text from the Reusable Text Library
        if (config && config.reusableText) {
            const reusableRegex = /{reusable_([^}]+)}/g;
            output = output.replace(reusableRegex, (match, key) => {
                return config.reusableText[key] !== undefined ? config.reusableText[key] : match;
            });
        }
        
        // Replace {variable_name} with actual data. If missing, leave a placeholder
        const regex = /{([^}]+)}/g;
        output = output.replace(regex, (match, key) => {
            // Check if there is data, or if it evaluates essentially empty
            if (formData[key] !== undefined && formData[key] !== "") {
                // If it matches a standardized call result, auto-swap to Reusable Text Library phrase to save typing
                if (key === 'contact_result') {
                    if (formData[key] === "Advised to monitor product" && config.reusableText.monitor_advisement) {
                        return config.reusableText.monitor_advisement;
                    }
                    if (formData[key] === "No Answer / Left Voicemail" && config.reusableText.voicemail_left) {
                        return config.reusableText.voicemail_left;
                    }
                    if (formData[key] === "Call not required" && config.reusableText.not_required) {
                        return config.reusableText.not_required;
                    }
                }
                return formData[key];
            } else if (config && config.activeProfileFields && config.activeProfileFields.find(f => f.id === key && f.visibleIf)) {
                // If this is a hidden conditional field, omit it cleanly rather than showing bracket tags
                 if (!DecisionEngine.checkCondition(config.activeProfileFields.find(f=>f.id === key).visibleIf, formData)) {
                     return ""; // Return blank if it's gracefully hidden
                 }
            }
            
            // If the field is totally empty and optional, we will output empty string, and then we will clean up labels later
            if (key === 'custom_notes' && (!formData[key] || formData[key] === "")) {
                return "";
            }

            // Return empty string for any empty field instead of brackets, so we can clean up labels globally
            return ""; 
        });

        // Clean up empty fields and their labels.
        // We cannot blindly split by '|' because the raw parsed alert string contains pipes natively (e.g. US|100|...), which breaks them with padding!
        // Instead, we will look for specific patterns: " Label: |" or " Label:   |" and remove them carefully.

        // Remove dangling label structures that evaluated strictly empty immediately preceding a literal " | " block separator
        // We match any characters except pipes leading up to a colon, followed by spaces, and then a pipe or end of line.
        // We include an optional trailing slash because of 'Affected Rack/'
        output = output.replace(/\s*[^|:]+:\s*(?=\||$)/g, "");

        // Additionally fix empty parenthesis structures generated by missing config values "( )"
        output = output.replace(/\s*\(\s*\)/g, "");

        // General cleanup for weird dangling pipes dynamically shifted
        // This removes duplicate pipes " | | " -> " | " and trailing pipes.
        output = output.replace(/(\|\s*){2,}/g, "| ").replace(/^\s*\|\s*/, "").replace(/\s*\|\s*$/, "");

        return output;
    }
};